#!/bin/sh
aws s3 --endpoint-url=https://storage.yandexcloud.net sync ./ s3://the-graduate-src/assets/ \
--exclude "*" \
--include "*mp3" \
--include "*png" \
--include "*jpg" \
--include "*jpeg" \
--include "*ogv" \
--include "*wav" \
--include "*ogg" \
--include "*exe" \
--include "*dmg" 